{
 "title": "ADA and BTC Live Price, Projections, Portfolios, ADA Live Stake",
 "description": "Cardano Mainnet Blockchain Stats & Nodes Monitor",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Portfolios Traking (Examples)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {}
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "250000 * adaprice_eur", "legendFormat": "Total Holding 250000 ADA =" },
      { "expr": "100000 * adaprice_eur", "legendFormat": "Wallet_1 100000 ADA =" },
      { "expr": "70000 * adaprice_eur", "legendFormat": "Wallet_2  70000 ADA =" },
      { "expr": "45000 * adaprice_eur", "legendFormat": "Wallet_3  45000 ADA =" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "adaprice_eur", "legendFormat": "1 ₳ = EUR" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 + (adaprice_usd - adaprice_eur)",
       "legendFormat": "1 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Projections, Targets Prices Eur to Usd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {}
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "adaprice_eur", "legendFormat": "1 ₳ = EUR" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "adaprice_usd", "legendFormat": "1 ₳ = USD" }
     ]
    },
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {}
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 + (adaprice_usd - adaprice_eur)",
       "legendFormat": "1 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1.1 * (1 + (adaprice_usd - adaprice_eur))",
       "legendFormat": "1.1 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1.2 * (1 + (adaprice_usd - adaprice_eur))",
       "legendFormat": "1.2 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1.3 * (1 + (adaprice_usd - adaprice_eur))",
       "legendFormat": "1.3 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1.4 * (1 + (adaprice_usd - adaprice_eur))",
       "legendFormat": "1.4 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1.5 * (1 + (adaprice_usd - adaprice_eur))",
       "legendFormat": "1.5 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "2 * (1 + (adaprice_usd - adaprice_eur))",
       "legendFormat": "2 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "3 * (1 + (adaprice_usd - adaprice_eur))",
       "legendFormat": "3 EUR/ADA =  USD"
      }
     ]
    },
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {}
     ]
    },
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": " ADA and Bitcoin Live Price", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "adaprice_eur", "legendFormat": "1 ₳ = EUR" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "adaprice_usd", "legendFormat": "1 ₳ = USD" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bitcoinprice_eur", "legendFormat": "1 BTC = EUR" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bitcoinprice_usd", "legendFormat": "1 BTC = USD" }
   ]
  },
  {
   "title": "ADA/EUR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "adaprice_eur", "legendFormat": "1 ₳ = EUR" }
   ]
  },
  {
   "title": "BTC/EUR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "bitcoinprice_eur", "legendFormat": "1 BTC = EUR" }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ADA Market Cap EUR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "ada_mcap_eur", "legendFormat": "ADA MCap" }
   ]
  },
  {
   "title": "ADA Vol 24h EUR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "ada_vol24h_eur", "legendFormat": "ADA Vol 24h EUR" }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "USD/EUR Change Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "usd_eur_rates_rate", "legendFormat": "USD/EUR Change Rate" }
   ]
  },
  {
   "title": "USD/EUR Change Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "usd_eur_rates_rate" }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cardano ADA Live Stake: ADA, USD, EUR + TXs OUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 22, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(global_total_staked / 1000000) ",
     "legendFormat": "Live Stake ADA"
    }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 17, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "(global_total_staked / 1000000) * (adaprice_eur)",
     "legendFormat": "Live Stake EUR"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(global_total_staked / 1000000) * adaprice_usd",
     "legendFormat": "Live Stake USD"
    }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ADA Price Projection vs USDT, ETH, BTC Market Cap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Current ADA Price USD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "adaprice_usd" }
     ]
    },
    {
     "title": "ADA Price USD vs ETH MCap",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(eth_marketcap / (global_ada_circ / 1000000))"
      }
     ]
    },
    {
     "title": "ADA Price USD vs BTC MCap",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(btc_marketcap / (global_ada_circ / 1000000))"
      }
     ]
    },
    {
     "title": "Current ADA Price EUR",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "adaprice_eur" }
     ]
    },
    {
     "title": "ADA Price EUR vs ETH MCap",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(eth_marketcap / (global_ada_circ / 1000000) * usd_eur_rates_rate)"
      }
     ]
    },
    {
     "title": "ADA Price EUR vs BTC MCap",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(btc_marketcap / (global_ada_circ / 1000000) * usd_eur_rates_rate)"
      }
     ]
    },
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}